default: &default
  timeout: 5000
  adapter: postgresql
  encoding: utf8
  database: come2eat_dev
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: come2eat_test

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
